### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by Shamad1** [Lykrast/GunsWithoutRoses#10]
[ru_ru.zip](https://github.com/Lykrast/GunsWithoutRoses/files/7962208/ru_ru.zip)

**Comment by Lykrast** [comment]
If you want to submit a translation, please use a Pull Requset.

**Comment by Shamad1** [comment]
I don't know how to use GitHub. I did not understand the sequence of actions that needs to be done in a pull request. I just wanted to help translate.
