### ISSUE TITLE
Ammo Storage/Usage

### ISSUE THREAD

**Issue by blockbreaker1361** [Lykrast/GunsWithoutRoses#11]
Mod suggestion-How about making an ammo box/crate/satchel that could hold all of your ammo so that it doesn't take up so much space in your inventory. Also, the guns could pull the ammo directly from the storage medium.

**Comment by Lykrast** [comment]
Out of scope for this mod, but it's doable. Guns pull ammo the same way as Bows and Crossbows pull their ammo, so if someone makes a quiver mod it can work with the guns.
