### ISSUE TITLE
Shooting unreasonably takes into account player vertical velocity, resulting in aim not toward crosshair

### ISSUE THREAD

**Issue by Colin-J-Wood** [Lykrast/GunsWithoutRoses#15]
Scenario: I am trying to use a technique in my modpack where I fire a gun whilst jumping.

What happens: the mathematics of the bullet's travel adds the velocity of the player's vertical/horizontal movement, which is unexpected as bullets should be flying toward the crosshair instead.  this results in, say, when the player jumps and is rising whilst taking the shot, the bullet will diagonally fly upwards, rather than straight ahead.  same with whilst falling, making the bullet fly downward so fast you miss the shot by several blocks, not because your crosshair missed, but because the bullet took your velocity into account when firing.

**Comment by Lykrast** [comment]
I'll see what I can do.

**Comment by Colin-J-Wood** [comment]
awaiting for this change to be backported to 1.16.5

**Comment by Lykrast** [comment]
I'm not supporting 1.16 anymore.

**Comment by Colin-J-Wood** [comment]
If i fork it myself and fix it, would you push it to curseforge, or should I simply spend time figuring out the other things to fix things up and post it on my own curseforge page.
