### ISSUE TITLE
License request for ExplodingCreeper/GunsWithoutRoses

### ISSUE THREAD

**Issue by Kaleidio** [Lykrast/GunsWithoutRoses#21]
Hiya, been a long time, thank you so much for the codebase.

However, as the gun mod of Kaleidio's Guns has evolved, a ton of what was once Guns Without Roses has evolved.

The two repositories are currently in a state over 500 commits apart, wherein only about 40% of the original codebase remains.  Please note only the 1.16.5 branch of the fork has ever been worked on or built to be submitted on CurseForge.

This issue is a license request/question to gather your opinion on your implementation of licensing.

From what I recall, the code itself is MIT licensed, which is fine.  However I am aware that visual assets are copyrighted by your artist.

I just need some verification that, if I were to replace all copyrighted assets in the mod, that I would be able to create a new repository and let our mods go their separate ways?

If there is anything else that is copyrighted that I have missed, or something that you request be revamped on Kaleidio's Guns to make it less like Guns Without Roses, to retain your rights to intellectual property, please let me know in this issue or in DM's on discord via `kaleidio`

I do recommend having a play with Kaleidio's Guns to see what I mean about how sheer the difference has become.

Hope to work with you again soon, cheers.

**Comment by Lykrast** [comment]
* Textures in GWR were (re)made by ViviSpook (the original ones were by me), I haven't asked them about it, but personally I would like you to have different textures.
* Sounds were made with CC0 sound effects from freesound.org , you can keep them if you want.
* Code is MIT so if you respect that it's fine.

So like as long as people can't mix your fork with GWR (which from a quick look at the curseforge page should be fine except for the current textures), it should be fine.

**Comment by Kaleidio** [comment]
Thank you so much for the response.  I'll replace the textures and keep the credit on the curseforge page.  Cheers.
