### ISSUE TITLE
Data driven bullets

### ISSUE THREAD

**Issue by lbowenwest** [Lykrast/GunsWithoutRoses#4]
Not sure if this is something you would like to do, but how do you feel about adding the ability for bullets and bullet behaviours (eg knockback and damage amount and effect on hit) to be defined by data?

This would allow pack developers (and yourself) to add new bullets with custom behaviour without having to make an addon mod

**Comment by Lykrast** [comment]
Maybe in an addon but it's not something I want to do in the main mod personally.

**Comment by lbowenwest** [comment]
Fair enough. Would probably be a bit of a deviation from the main mod.
