### ISSUE TITLE
[Suggestion] Elemental bullets

### ISSUE THREAD

**Issue by HaxtonSale1** [Lykrast/GunsWithoutRoses#7]
Since (8 Iron Bullets) + (1 Blaze Powder) = (8 Blaze Bullets), 

(8 Iron Bullets) + (1 Blizz Powder) = (8 Blizz Bullets)
Similar for Blitz and Basalz powders

Blizz bullets slow enemies down, obviously
Blitz bullets summons lightning where landed
Basalz bullets have large knockback

**Comment by Lykrast** [comment]
Mod compat will be kept to a separate mod. I'll note these down as candidates though.
