### ISSUE TITLE
[Suggestion] Make Iron Bullets able to break glass blocks

### ISSUE THREAD

**Issue by JDLENL** [Lykrast/GunsWithoutRoses#9]
Title. If I'm firing a shotgun's worth of heavy iron balls into a glass window, it's gonna shatter. Or at least, I think it should. Flint bullets would probably shatter, but at least iron should break through. Probably make this configurable, though?

**Comment by Lykrast** [comment]
These bullets are not gonna destroy any blocks. Maybe block breaking bullets in an addon, but not in the base mod.
